---
tmp_dir: ./tmp
config_dir: ./configs
config_diff_dir: ./config_diff
log_dir: ./logs
ansible_user: ansible
ansible_ssh_pass: ansible123

# BEGIN ANSIBLE MANAGED BLOCK
common: 
  BGP_ASN: 65400
  CORE_SUBNET: 10.1.1.0/24
  DNS:
  - 172.20.1.1
  - 172.20.1.15
  LOOPBACK_SUBNET: 10.100.1.0/24
  MGMT_GW: 172.20.2.1
  MGMT_PREFIXES:
  - 192.168.0.0/24
  - 10.8.0.0/24
  - 172.20.2.0/24
  MGMT_SUBNET: 172.20.2.0/28
  MTU: 1500
  OSPF_AREA: 0
  OSPF_PID: 1
  P2P_PREFIX: 31
  USERS:
  -   passwd: 14161C180506262E757A60
      username: ansible


p2p_ip:
  den-core01:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.8/31 , peer: den-core02, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.9/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.3/31 , peer: syd-core01, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.2/31}
  den-core02:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.9/31 , peer: den-core01, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.8/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.11/31 , peer: str-core02, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.10/31}
  str-core01:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.6/31 , peer: str-core02, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.7/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.5/31 , peer: syd-core02, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.4/31}
  str-core02:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.7/31 , peer: str-core01, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.6/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.10/31 , peer: den-core02, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.11/31}
  syd-core01:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.0/31 , peer: syd-core02, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.1/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.2/31 , peer: den-core01, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.3/31}
  syd-core02:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.1/31 , peer: syd-core01, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.0/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.4/31 , peer: str-core01, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.5/31}

lo_ip:
  den-core01: 10.100.1.1/32
  syd-core01: 10.100.1.2/32

mgmt_net:
  den-core01 : { intf: MgmtEth0/0/CPU0/0, ip: 172.20.2.4/28 }
  syd-core01 : { intf: MgmtEth0/RP0/CPU0/0, ip: 172.20.2.2/28 }

# END ANSIBLE MANAGED BLOCK
